backend: local
backup_directory: /home/INGInious/backup
local-config: {}
mongo_opt:
    database: INGInious
    host: localhost
plugins: []
superadmins:
- superadmin
tasks_directory: /home/INGInious/tasks
use_minified_js: true
plugins:
  - plugin_module: inginious.frontend.webapp.plugins.statistics
  - plugin_module: inginious.frontend.webapp.plugins.task_cache
  - plugin_module: inginious.frontend.webapp.plugins.grader_generator
  - plugin_module: inginious.frontend.webapp.plugins.reference_solution
