backend: local
backup_directory: /opt/INGInious/backup
local-config: {}
mongo_opt:
    database: INGInious
    host: localhost
plugins: []
superadmins:
- superadmin
tasks_directory: /opt/INGInious/tasks
use_minified_js: false
plugins:
    - plugin_module: inginious.frontend.webapp.plugins.statistics
