version: "3"

services:
  linter-service:
    image: unjudge/linter-web-service
    ports:
      - "${LINTER_PORT}:4567"
    restart: always
    deploy:
      resources:
        limits:
          memory: 3000M # Limit memory usage to 3GB
          cpus: "2" # Set a custom cpu usage
  python-tutor:
    image: unjudge/onlinepythontutor
    environment:
      - COKAPI_ENDPOINT=uncode.unal.edu.co/cokapi
      - PY_CMD=python3
    ports:
      - "${PYTHON_TUTOR_PORT}:8003"
    restart: always
    deploy:
      resources:
        limits:
          memory: 2000M # Limit memory usage to 2GB
