version: "3"

services:
  linter-service:
    image: unjudge/linter-web-service
    ports:
      - "${LINTER_PORT}:4567"
    restart: always
  python-tutor:
    image: unjudge/onlinepythontutor
    environment:
      - COKAPI_ENDPOINT=uncode.unal.edu.co/cokapi
    ports:
      - "${PYTHON_TUTOR_PORT}:8003"
    restart: always
