version: "3"

services:
  linter-service:
    image: unjudge/linter-web-service
    ports:
      - "${LINTER_PORT}:4567"
  python-tutor:
    image: unjudge/onlinepythontutor
    ports:
      - "${PYTHON_TUTOR_PORT}:8003"
  cokapi:
    image: unjudge/cokapi
    ports:
      - "${COKAPI_PORT}:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: mongo:3.4
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongo-data:/data/db
  inginious:
    image: unjudge/inginious
    ports:
      - "${INGINIOUS_PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${JUDGE_HOME}/tasks:/home/INGInious/tasks
      - ${JUDGE_HOME}/backup:/home/INGInious/backup
      - ${JUDGE_HOME}/configuration.yaml:/home/INGInious/configuration.yaml
    depends_on:
      - "db"
      - "cokapi"
      - "python-tutor"
      - "linter-service"
    command: ./inginious-webapp --host 0.0.0.0
volumes:
  mongo-data:
