version: "3"

services:
  linter-service:
    image: unjudge/linter-web-service
    ports:
      - "${LINTER_PORT}:4567"
    restart: always
    deploy:
      resources:
        limits:
          memory: 1000M # Limit memory usage to 1GB
          cpus: "1" # Set a custom cpu usage
  python-tutor:
    image: unjudge/onlinepythontutor
    environment:
      - "COKAPI_ENDPOINT=${UNCODE_DOMAIN}/cokapi" # Update with the correct domain or IP where python tutor is deployed
      - PY_CMD=python3
    ports:
      - "${PYTHON_TUTOR_PORT}:8003"
    restart: always
    deploy:
      resources:
        limits:
          memory: 2000M # Limit memory usage to 2GB
