#!/bin/bash

if [ ! -f docker-compose.yml ]; then
    echo "docker-compose.yml not found, cd into to Deployment folder"
    exit
fi

echo "Restarting python tutor"
docker-compose up -d --no-deps python-tutor
docker-compose restart python-tutor

# TODO put cokapi restart logic here

echo "Python tutor restarted successfully"
