{
 "title": "UNCode Main server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"main\", job=\"node-exporter\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"main\", job=\"node-exporter\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=\"main\", job=\"node-exporter\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"main\", job=\"node-exporter\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Disk space ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=\"main\", job=\"node-exporter\"}) - sum(node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=\"main\", job=\"node-exporter\"}) )/ sum(node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=\"main\", job=\"node-exporter\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time since the last boot",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"main\", job=\"node-exporter\"}",
     "legendFormat": "uptime"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 9, "x": 14, "y": 1 } },
  {
   "title": "RAM Total",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"main\", job=\"node-exporter\"}",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "singlestat",
   "description": "Total SWAP",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"main\", job=\"node-exporter\"}",
     "legendFormat": "SWAP"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"main\", job=\"node-exporter\"} - node_memory_MemAvailable_bytes{instance=\"main\", job=\"node-exporter\"}) / node_memory_MemTotal_bytes{instance=\"main\", job=\"node-exporter\"}) * 100"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 5 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"main\", job=\"node-exporter\"} - node_memory_SwapFree_bytes{instance=\"main\", job=\"node-exporter\"})"
    }
   ]
  },
  { "title": "Docker Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{instance=\"main\",job=\"docker\",state=\"running\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "engine_daemon_container_states_containers{instance=\"main\",job=\"docker\",state=\"paused\"}",
     "legendFormat": "Paused"
    },
    {
     "expr": "engine_daemon_container_states_containers{instance=\"main\",job=\"docker\",state=\"stopped\"}",
     "legendFormat": "Stopped"
    }
   ]
  },
  {
   "title": "UNCode Containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(time()-container_last_seen{name=\"uncode_mongo_express\", instance=\"main\", job=\"cadvisor\"}<=60) or vector(0)",
     "legendFormat": "Mongo Express"
    },
    {
     "expr": "count(time()-container_last_seen{name=\"uncode_metabase\", instance=\"main\", job=\"cadvisor\"}<=60) or vector(0)",
     "legendFormat": "Metabase"
    }
   ]
  },
  {
   "title": "Use of Multiple Language containers [Beta]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count((time() - container_last_seen{instance=\"main\", job=\"cadvisor\", container_label_org_inginious_grading_name=\"multiple_languages\"})<=15)  OR vector(0)\n",
     "legendFormat": "Multiple Language"
    }
   ]
  },
  {
   "title": "Use of HDL containers [Beta]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count((time() - container_last_seen{instance=\"main\", job=\"cadvisor\", container_label_org_inginious_grading_name=\"HDL\"})<=15)  OR vector(0)\n",
     "legendFormat": "HDL"
    }
   ]
  },
  {
   "title": "Use of Notebooks [Beta]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count((time() - container_last_seen{instance=\"main\", job=\"cadvisor\", container_label_org_inginious_grading_name=\"Notebook\"})<=15)  OR vector(0)",
     "legendFormat": "Use of Notebooks"
    }
   ]
  },
  { "title": "Docker Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\", instance=\"main\", job=\"cadvisor\"}[5m])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Used Memory per Container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\",instance=\"main\", job=\"cadvisor\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Server Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",instance=\"main\", job=\"node-exporter\"}[5m])) * 25",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",instance=\"main\", job=\"node-exporter\"}[5m])) * 25",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",instance=\"main\", job=\"node-exporter\"}[5m])) * 25",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"main\", job=\"node-exporter\"}[5m])) * 25",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",instance=\"main\", job=\"node-exporter\"}[5m])) * 25",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",instance=\"main\", job=\"node-exporter\"}[5m]))*25",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"main\", job=\"node-exporter\"} -  node_memory_MemAvailable_bytes{instance=\"main\", job=\"node-exporter\"}",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"main\", job=\"node-exporter\"} - node_memory_MemFree_bytes{instance=\"main\", job=\"node-exporter\"}",
     "legendFormat": "RAM Cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"main\", job=\"node-exporter\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"main\", job=\"node-exporter\"}",
     "legendFormat": "RAM Total"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"main\", job=\"node-exporter\"} - node_memory_SwapFree_bytes{instance=\"main\", job=\"node-exporter\"})",
     "legendFormat": "SWAP Used"
    },
    {
     "expr": "(node_memory_SwapFree_bytes{instance=\"main\", job=\"node-exporter\"})",
     "legendFormat": "SWAP Free"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=\"main\", job=\"node-exporter\"}",
     "legendFormat": "SWAP Total"
    }
   ]
  },
  { "title": "FileSystems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "/",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs', mountpoint=\"/\", instance=\"main\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_avail_bytes{device!~'rootfs', mountpoint=\"/\", instance=\"main\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~'rootfs', mountpoint=\"/\", instance=\"main\"} - node_filesystem_avail_bytes{device!~'rootfs', mountpoint=\"/\", instance=\"main\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "/home",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/home\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/home\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/home\"} - node_filesystem_avail_bytes{instance=\"main\", job=\"node-exporter\",  device!~'rootfs', mountpoint=\"/home\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "/datos",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/datos\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/datos\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/datos\"} - node_filesystem_avail_bytes{instance=\"main\", job=\"node-exporter\",  device!~'rootfs', mountpoint=\"/datos\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "/usr",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/usr\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/usr\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/usr\"} - node_filesystem_avail_bytes{instance=\"main\", job=\"node-exporter\",  device!~'rootfs', mountpoint=\"/usr\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "/opt",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/opt\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/opt\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/opt\"} - node_filesystem_avail_bytes{instance=\"main\", job=\"node-exporter\",  device!~'rootfs', mountpoint=\"/opt\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "/boot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/boot\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/boot\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/boot\"} - node_filesystem_avail_bytes{instance=\"main\", job=\"node-exporter\",  device!~'rootfs', mountpoint=\"/boot\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "/var",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/var\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/var\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/var\"} - node_filesystem_avail_bytes{instance=\"main\", job=\"node-exporter\",  device!~'rootfs', mountpoint=\"/var\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "/var/log",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/var/log\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/var/log\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/var/log\"} - node_filesystem_avail_bytes{instance=\"main\", job=\"node-exporter\",  device!~'rootfs', mountpoint=\"/var/log\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "/var/www",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/var/www\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_filesystem_avail_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/var/www\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=\"main\", job=\"node-exporter\", device!~'rootfs', mountpoint=\"/var/www\"} - node_filesystem_avail_bytes{instance=\"main\", job=\"node-exporter\",  device!~'rootfs', mountpoint=\"/var/www\"}",
     "legendFormat": "Used"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "UNCode Services",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=\"main\", job=\"node-exporter\", name=\"docker.service\", state=\"active\"}",
     "legendFormat": "Docker"
    },
    {
     "expr": "node_systemd_unit_state{instance=\"main\", job=\"node-exporter\", name=\"mongod.service\", state=\"active\"}",
     "legendFormat": "Mongo"
    },
    {
     "expr": "node_systemd_unit_state{instance=\"main\", job=\"node-exporter\", name=\"lighttpd.service\", state=\"active\"}",
     "legendFormat": "lighttpd"
    },
    {
     "expr": "node_systemd_unit_state{instance=\"main\", job=\"node-exporter\", name=\"nginx.service\", state=\"active\"}",
     "legendFormat": "nginx"
    },
    {
     "expr": "node_systemd_unit_state{instance=\"main\", job=\"node-exporter\", name=\"backend.service\", state=\"active\"}",
     "legendFormat": "Backend"
    },
    {
     "expr": "node_systemd_unit_state{instance=\"main\", job=\"node-exporter\", name=\"docker_agent.service\", state=\"active\"}",
     "legendFormat": "Docker Agent"
    },
    {
     "expr": "node_systemd_unit_state{instance=\"main\", job=\"node-exporter\", name=\"mcq_agent.service\", state=\"active\"}",
     "legendFormat": "MCQ"
    }
   ]
  },
  {
   "title": "Monitor Services",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_systemd_unit_state{instance=\"main\", job=\"node-exporter\", name=\"prometheus.service\", state=\"active\"}",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "node_systemd_unit_state{instance=\"main\", job=\"node-exporter\", name=\"node_exporter.service\", state=\"active\"}",
     "legendFormat": "Node Exporter"
    },
    {
     "expr": "node_systemd_unit_state{instance=\"main\", job=\"node-exporter\", name=\"grafana-server.service\", state=\"active\"}",
     "legendFormat": "Grafana"
    },
    {
     "expr": "count(time()-container_last_seen{instance=\"main\", job=\"cadvisor\", name=\"cadvisor_cadvisor_1\"}<=60) or vector(0)",
     "legendFormat": "cAdvisor"
    }
   ]
  },
  {
   "title": "Reporting in Prometheus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"localhost:9090\"}",
     "legendFormat": "Prometheus"
    },
    {
     "expr": "up{instance=\"localhost:9091\"}",
     "legendFormat": "Grafana"
    },
    {
     "expr": "up{instance=\"main\", job=\"node-exporter\"}",
     "legendFormat": "Node Exporter"
    },
    {
     "expr": "up{instance=\"main\", job=\"cadvisor\"}",
     "legendFormat": "cAdvisor"
    },
    {
     "expr": "up{instance=\"main\", job=\"docker\"}",
     "legendFormat": "Docker Metrics"
    }
   ]
  }
 ]
}