{
 "title": "Daily report - Uncode",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Automated reports", "type": "alertlist", "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\",instance=\"SERVER_IP:CADVISOR_PORT\"}[5m])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",instance=\"SERVER_IP:9100\"}[5m])) * 25",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",instance=\"SERVER_IP:9100\"}[5m])) * 25",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",instance=\"SERVER_IP:9100\"}[5m])) * 25",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"SERVER_IP:9100\"}[5m])) * 25",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"irq\",mode!=\"softirq\",instance=\"SERVER_IP:9100\"}[5m])) * 25",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",instance=\"SERVER_IP:9100\"}[5m]))*25",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"SERVER_IP:9100\"} -  node_memory_MemAvailable_bytes{instance=\"SERVER_IP:9100\"}",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"SERVER_IP:9100\"} - node_memory_MemFree_bytes{instance=\"SERVER_IP:9100\"}",
     "legendFormat": "RAM Cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"SERVER_IP:9100\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"SERVER_IP:9100\"}",
     "legendFormat": "RAM Total"
    }
   ]
  }
 ]
}