#!/bin/bash
set -e

if [ "$1" == "push" ]
then
    echo -e "Pushing backups to remote...\n"
    git push
    echo -e "\nBackup(s) pushed successfully" 
elif [ "$1" == "create" ]
then
    echo -e "Creating backup...\n"
    rm -r copyData/
    mongodump -d INGInious -o copyData
    git add --all

    dt=$(date '+%d/%m/%Y %H:%M:%S');
    git commit -m "$dt"

    echo -e "\nBackup commited successfully"
elif [ "$1" == "restore" ]
then
    if [ -z "$2" ]
    then
        echo -e "Restoring $2 backup...\n"
        git checkout $2
    else
        echo -e "Restoring HEAD backup...\n"
    fi

    mongorestore --db INGInious copyData/INGInious/
else
    echo -e "Usage:\nuncode_backup push\nuncode_backup create\nuncode_backup restore\n"
    echo -e "uncode_backup restore COMMIT_HASH\n"
fi
