#!/bin/bash

cd $DEPLOYMENT_HOME

# Restart and update python tutor

echo "Updating and restarting python-tutor..."
docker pull unjudge/onlinepythontutor
docker pull unjudge/opt-cpp-backend
docker-compose --compatibility up -d --no-deps python-tutor
docker-compose --compatibility restart python-tutor

echo "Python tutor restarted successfully and images are up to date."

# Restart cokapi service
sudo service cokapi restart

echo "Tutor Cokapi service restarted successfully"
