#!/bin/bash

if [ "$1" == "activate" ]
then
  sudo mv /usr/share/nginx/html/maintenance_off.html /usr/share/nginx/html/maintenance_on.html
elif [ "$1" == "deactivate" ]
then
  sudo mv /usr/share/nginx/html/maintenance_on.html /usr/share/nginx/html/maintenance_off.html
else
  echo "Usage: the only options available are 'activate' and 'deactivate'."
fi