#!/bin/bash
set -e

if [ "$1" == "upload" ]
then
    echo -e "Uploading backups to remote...\n"
    if [ ! -z "$(gdrive list --no-header)" ]
    then
      gdrive delete $(gdrive list --no-header | cut -d ' ' -f1)
    fi

    gdrive upload $(ls *.tar.gz)

    rm -f ~/dbBackupID
    echo $(gdrive list --no-header | cut -d ' ' -f1) > ~/dbBackupID
    rm -rf *
    echo -e "\nBackup uploaded successfully"
elif [ "$1" == "create" ]
then
    echo -e "Creating backup...\n"

    rm -rf *
    mongodump -d INGInious -o copyData

    dt=$(date '+%d-%m-%Y-%H.%M.%S');
    tar -zcvf "$dt.tar.gz" copyData

    echo -e "\nBackup created successfully"
elif [ "$1" == "restore" ]
then
    gdrive download $(cat ~/dbBackupID)

    tar -zxvf *.tar.gz

    mongorestore --db INGInious copyData/INGInious/

    rm -rf *
    echo -e "\nBackup restored successfully"
else
    echo -e "Usage:\nuncode_database_backup push\nuncode_database_backup create\nuncode_database_backup restore"
fi
