#!/bin/bash

cd $DEPLOYMENT_HOME

echo "Updating and restarting linter-web-service..."
docker-compose up -d --no-deps linter-service
docker-compose restart linter-service

echo "Linter-web-service restarted successfully and image is up to date."
