#!/bin/bash

cd $DEPLOYMENT_HOME

echo "Updating and restarting linter-web-service..."
docker pull unjudge/linter-web-service
docker-compose --compatibility up -d --no-deps linter-service
docker-compose --compatibility restart linter-service

echo "Linter-web-service restarted successfully and image is up to date."
