#!/bin/bash
echo "Restarting uncode..."

echo "Restarting lighttpd 1/3"
sudo service lighttpd restart

echo "Restarting nginx 2/3"
sudo service nginx restart

echo "Restarting mongod 3/3"
sudo service mongod restart

echo "Uncode restarted successfully"
