#!/bin/bash

cd $DEPLOYMENT_HOME

#Restart and update docker container
echo "Updating and restarting python-tutor..."
docker-compose up -d --no-deps python-tutor
docker-compose restart python-tutor

echo "python-tutor restarted successfully and image is up to date."

#Restart cokapi service
sudo service cokapi restart
echo "Tutor (python-tutor + cokapi) restarted successfully"
