#!/bin/bash
echo "Restarting uncode..."

echo "Restarting lighttpd 1/5"
sudo service lighttpd restart

echo "Restarting backend 2/5"
sudo service backend restart

echo "Restarting agents 3/5"
sudo service mcq_agent restart
sudo service docker_agent restart

echo "Restarting mongod 4/5"
sudo service mongod restart

echo "Restarting nginx 5/5"
sudo service nginx restart
echo "Uncode restarted successfully"
